In [876]:
import numpy as np
import pandas as pd
import math 
import os
import glob

In [877]:
import warnings
warnings.filterwarnings('ignore')

In [878]:
colnum = 476
merged_df = pd.DataFrame(columns = range(0,52))

In [879]:
folders = ['\D', '\(NonD)']

In [880]:
for folder in folders:
    path = os.getcwd() + folder
    csv_files = glob.glob(os.path.join(path, "*.csv"))
    
    for file in csv_files:
        df = pd.read_csv(file, header=None)
        prev_row=[]
        dist=[]
        
        for i in range(0, colnum+1):
            j=0
            if(df.shape[0]-1 <= i): #if records are less then append 0
                x=0
                y=0
            else:
                for row in df.iloc[i,:]: #get x and y from row
                    if(j==0):
                        x = row
                    if(j==1):
                        y= row
                    j+=1

            if prev_row: 
                if(x==0 and y==0): # if there is no record left then distance =0
                    distance=0;
                else:
                    distance = round(math.sqrt(((x - prev_row[0])**2) + ((y-prev_row[1])**2)),2) #Euclidean distance
                    distance= round(distance*distance,0)
                dist.append(distance)
                prev_row.clear() #update previous row
                prev_row.append(x)
                prev_row.append(y) 
            else:
                prev_row.append(x)
                prev_row.append(y)
        
        temp = pd.Series(x for x in dist) #convert it to series to append to dataframe
        #temp['length']= df.shape[0]
        temp = temp.sort_values()
        temp_1=temp[-50:].copy()
        temp_1 = temp_1.reset_index(drop=True)
        #print(temp_1)
        
        colname = str(temp_1.shape[0])
        filecolname = str(temp_1.shape[0]+1)
        #filecolname = str(colnum+1)
        
        if(folder=="\D"): #Labeling target
            temp_1[colname] = 'Dyslexia'
            #temp['200'] = 'Dyslexia'
        else:
            temp_1[colname] = 'Non-Dyslexia'
            #temp['200'] = 'Dyslexia'
        #temp[filecolname] = file[-10:]
        temp_1[filecolname] = file[-10:]
        
        #print(filecolname)
        
        #print(merged_df.shape)
        #merged_df = merged_df.append(temp_1, ignore_index=False)
        merged_df = pd.concat([merged_df,temp_1.to_frame().T], axis=0, ignore_index=True)
        
        

In [881]:
merged_df.drop([50,51],axis=1, inplace=True)

In [882]:
merged_df[filecolname].value_counts().sum()

199

In [883]:
merged_df.shape

(199, 52)

In [884]:
merged_df

0         1         2         3         4         5         6  \
0         4.0       4.0       5.0       5.0       5.0       5.0       9.0   
1        13.0      16.0      17.0      17.0      17.0      18.0      18.0   
2         8.0       9.0       9.0       9.0      13.0      13.0      17.0   
3        34.0      40.0      41.0      52.0      58.0      61.0      64.0   
4         5.0       5.0       5.0       5.0       5.0       5.0       5.0   
..        ...       ...       ...       ...       ...       ...       ...   
194  151586.0  151648.0  151648.0  151648.0  151718.0  152116.0  154292.0   
195  169357.0  169447.0  169447.0  169447.0  169653.0  169736.0  169736.0   
196  143558.0  143618.0  143937.0  144066.0  144157.0  144354.0  144872.0   
197  152662.0  152662.0  152662.0  152662.0  152662.0  152826.0  153077.0   
198  147279.0  149761.0  149761.0  150366.0  150761.0  151158.0  151827.0   

            7         8         9  ...        42        43        44  \
0         9.0       9.0      10.0  ...    1961.0    2025.0    2225.0   
1        20.0      20.0      20.0  ...    1730.0    1813.0    1865.0   
2        17.0      17.0      20.0  ...     545.0     565.0     601.0   
3        64.0      65.0      68.0  ...     842.0    1394.0    1418.0   
4         8.0       8.0       8.0  ...     580.0    1201.0    2178.0   
..        ...       ...       ...  ...       ...       ...       ...   
194  156136.0  161491.0  162296.0  ...  169934.0  169934.0  169958.0   
195  169736.0  169934.0  170214.0  ...  174415.0  175452.0  176014.0   
196  145588.0  146306.0  146452.0  ...  176787.0  177224.0  177561.0   
197  153077.0  153077.0  153077.0  ...  163054.0  163054.0  163143.0   
198  151983.0  151999.0  152100.0  ...  171794.0  171860.0  171968.0   

           45        46        47        48        49            50  \
0      3250.0    3481.0    3796.0    5300.0   10420.0      Dyslexia   
1      2357.0    3604.0   83955.0  107276.0  114636.0      Dyslexia   
2       612.0     685.0    1450.0    9860.0  106283.0      Dyslexia   
3      1690.0    1700.0    1865.0    2053.0   10426.0      Dyslexia   
4      3280.0    3645.0    4394.0    9657.0   87072.0      Dyslexia   
..        ...       ...       ...       ...       ...           ...   
194  170255.0  170313.0  170503.0  170503.0  171197.0  Non-Dyslexia   
195  176450.0  176888.0  176888.0  176888.0  177654.0  Non-Dyslexia   
196  177654.0  177991.0  178329.0  178667.0  179208.0  Non-Dyslexia   
197  163313.0  163564.0  163887.0  164868.0  165527.0  Non-Dyslexia   
198  172109.0  172449.0  172449.0  172449.0  172748.0  Non-Dyslexia   

             51  
0     PM #2.csv  
1    .03 PM.csv  
2     PM #2.csv  
3     PM #3.csv  
4    .04 PM.csv  
..          ...  
194  deo-67.csv  
195  deo-68.csv  
196  deo-69.csv  
197  deo-70.csv  
198  deo-71.csv  

[199 rows x 52 columns]

In [885]:
data_df = merged_df.iloc[:,:-1]

# Seperating features and target

In [886]:
X = data_df.iloc[:,:-1]
y = data_df.iloc[:, -1] 

In [887]:
y

0          Dyslexia
1          Dyslexia
2          Dyslexia
3          Dyslexia
4          Dyslexia
           ...     
194    Non-Dyslexia
195    Non-Dyslexia
196    Non-Dyslexia
197    Non-Dyslexia
198    Non-Dyslexia
Name: 50, Length: 199, dtype: object

# Splitting data

In [888]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 1)

# Scaling

In [889]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


#Scaling features and target 
X_train = sc_X.fit_transform(X_train)
y_train = le.fit_transform(y_train)

#Transform test set
X_test = sc_X.transform(X_test)
y_test = le.transform(y_test)

In [890]:
le.inverse_transform([1])

array(['Non-Dyslexia'], dtype=object)

In [942]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(sc_X, f)
    
with open('encoder.pkl', 'wb') as f:
    pickle.dump(le, f)

## SVC

In [891]:
#Initlializing model
from sklearn.svm import SVC # non-linear
classifier = SVC() 


from sklearn.model_selection import GridSearchCV

#Initializing different parameters that will be used in grid search 
parameters = [{'C':[0.25, 0.5, 0.75, 1], 'kernel':['rbf','linear', 'poly', 'sigmoid'], 'gamma':['scale', 'auto']}]
'''
Before using this below parameters were used to accuracy for each kernel: 'linear','poly','rbf','sigmoid' 
{'C':[0.25, 0.5, 0.75, 1],'gamma':['scale', 'auto'], 'epsilon':[0.2,0.5,0.7,1]}
'''

grid_search = GridSearchCV(estimator=classifier, 
                           param_grid=parameters,
                           scoring='accuracy',  #scoring method will be R square
                           cv=5,         #ten sets for cross validation
                           n_jobs=-1)     #n_jobs=-1 will use all the available processors

#Fitting it on train set
grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:",best_parameters)

Best Accuracy: 56.99 %
Best Parameters: {'C': 0.5, 'gamma': 'scale', 'kernel': 'poly'}


In [892]:
from sklearn.svm import SVC # non-linear
classifier = SVC(kernel='poly', C=0.5, gamma='scale') 
classifier.fit(X_train, y_train)

SVC(C=0.5, kernel='poly')

In [893]:
y_pred = classifier.predict(X_test)

In [894]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print("Accuracy", accuracy_score(y_test, y_pred))
print("Test:     ", y_test)
print("Predicted:", y_pred)

from sklearn.metrics import recall_score
print("Recall", recall_score(y_test, y_pred, pos_label=0, average='binary'))
from sklearn.metrics import precision_score
print("Precision", precision_score(y_test, y_pred, pos_label=0,  average='binary'))

# Low Recall

Confusion Matrix:
 [[23 17]
 [15 25]]
Accuracy 0.6
Test:      [1 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 1
 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1
 1 0 1 1 1 1]
Predicted: [1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0
 1 1 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 1 1
 0 0 1 0 1 1]
Recall 0.575
Precision 0.6052631578947368


## Random Forest

In [895]:
#Initlializing model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()


from sklearn.model_selection import GridSearchCV

#Initializing different parameters that will be used in grid search 
parameters = [{'n_estimators':[100, 150, 250, 300, 350, 400, 450], 'criterion':['gini', 'entropy', 'log_loss']}]

grid_search = GridSearchCV(estimator=classifier, 
                           param_grid=parameters,
                           scoring='accuracy',  #scoring method will be R square
                           cv=5,         #ten sets for cross validation
                           n_jobs=-1)     #n_jobs=-1 will use all the available processors

#Fitting it on train set
grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:",best_parameters)



Best Accuracy: 39.46 %
Best Parameters: {'criterion': 'gini', 'n_estimators': 100}


In [896]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(criterion='gini', n_estimators=350)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)


cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall ", recall_score(y_test, y_pred, pos_label=0, average='binary'))
print("Precision ", precision_score(y_test, y_pred, pos_label=0,  average='binary'))

print("Test:     ", y_test)
print("Predicted:", y_pred)

#Low Recall

Confusion Matrix:
 [[22 18]
 [19 21]]
Accuracy 0.5375
Recall  0.55
Precision  0.5365853658536586
Test:      [1 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 1
 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1
 1 0 1 1 1 1]
Predicted: [0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1
 0 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 1 0
 1 0 1 0 1 1]


## Naive Bayes

In [898]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)


cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall", recall_score(y_test, y_pred, pos_label=0, average='binary'))

print("Precision", precision_score(y_test, y_pred, pos_label=0,  average='binary'))

print("Test:     ", y_test)
print("Predicted:", y_pred)

#Low recall

Confusion Matrix:
 [[24 16]
 [19 21]]
Accuracy 0.5625
Recall 0.6
Precision 0.5581395348837209
Test:      [1 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 1
 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1
 1 0 1 1 1 1]
Predicted: [1 0 0 1 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0
 1 1 0 0 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 0 1 1
 0 0 0 0 0 1]


## KNN

In [899]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()

from sklearn.model_selection import GridSearchCV

#Initializing different parameters that will be used in grid search 
parameters = [{'n_neighbors':[3,5,7,9,11,13,15], 'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute']}]

grid_search = GridSearchCV(estimator=classifier, 
                           param_grid=parameters,
                           scoring='accuracy',  #scoring method will be R square
                           cv=5,         #ten sets for cross validation
                           n_jobs=-1)     #n_jobs=-1 will use all the available processors

#Fitting it on train set
grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:",best_parameters)

Best Accuracy: 52.03 %
Best Parameters: {'algorithm': 'ball_tree', 'n_neighbors': 11}


In [939]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=11, algorithm='ball_tree')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)


cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall", recall_score(y_test, y_pred, pos_label=0, average='binary'))

print("Precision", precision_score(y_test, y_pred, pos_label=0,  average='binary'))

print("Recall for Non dyslexic:", recall_score(y_test, y_pred, pos_label=1, average='binary'))

print("Precision for Non dyslexic:", precision_score(y_test, y_pred, pos_label=1,  average='binary'))

print("Test:     ", y_test)
print("Predicted:", y_pred)

#Good Recall for Dyslexic and Good Precision for Non Dyslexic

Confusion Matrix:
 [[32  8]
 [23 17]]
Accuracy 0.6125
Recall 0.8
Precision 0.5818181818181818
Recall for Non dyslexic: 0.425
Precision for Non dyslexic: 0.68
Test:      [1 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 1
 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1
 1 0 1 1 1 1]
Predicted: [0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0
 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1
 1 0 0 1 0 1]


In [941]:
import pickle
save_classifier = open('KNN_model.pkl','wb')
pickle.dump(classifier, save_classifier)
save_classifier.close

<function BufferedWriter.close>

In [935]:
import tensorflow as tf

ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=50, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=8, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=4, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=1024, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=1024, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=475, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=475, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=8, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=8, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 
ann.fit(X_train, y_train, batch_size = 5, epochs = 100)

Epoch 1/100
24/24 [==============================] - 0s 770us/step - loss: 0.7276 - accuracy: 0.4874
Epoch 2/100
24/24 [==============================] - 0s 676us/step - loss: 0.6957 - accuracy: 0.5042
Epoch 3/100
24/24 [==============================] - 0s 702us/step - loss: 0.6884 - accuracy: 0.5126
Epoch 4/100
24/24 [==============================] - 0s 732us/step - loss: 0.6946 - accuracy: 0.5294
Epoch 5/100
24/24 [==============================] - 0s 688us/step - loss: 0.6896 - accuracy: 0.5294
Epoch 6/100
24/24 [==============================] - 0s 709us/step - loss: 0.7105 - accuracy: 0.5126
Epoch 7/100
24/24 [==============================] - 0s 699us/step - loss: 0.6948 - accuracy: 0.5210
Epoch 8/100
24/24 [==============================] - 0s 739us/step - loss: 0.6980 - accuracy: 0.4958
Epoch 9/100
24/24 [==============================] - 0s 719us/step - loss: 0.7019 - accuracy: 0.5378
Epoch 10/100
24/24 [==============================] - 0s 741us/step - loss: 0.7153 - accura

24/24 [==============================] - 0s 696us/step - loss: 0.6750 - accuracy: 0.5546
Epoch 82/100
24/24 [==============================] - 0s 690us/step - loss: 0.6718 - accuracy: 0.5546
Epoch 83/100
24/24 [==============================] - 0s 705us/step - loss: 0.6826 - accuracy: 0.5378
Epoch 84/100
24/24 [==============================] - 0s 718us/step - loss: 0.6679 - accuracy: 0.5546
Epoch 85/100
24/24 [==============================] - 0s 666us/step - loss: 0.6823 - accuracy: 0.5546
Epoch 86/100
24/24 [==============================] - 0s 707us/step - loss: 0.6729 - accuracy: 0.5546
Epoch 87/100
24/24 [==============================] - 0s 696us/step - loss: 0.6744 - accuracy: 0.5210
Epoch 88/100
24/24 [==============================] - 0s 691us/step - loss: 0.6824 - accuracy: 0.5210
Epoch 89/100
24/24 [==============================] - 0s 717us/step - loss: 0.6631 - accuracy: 0.5882
Epoch 90/100
24/24 [==============================] - 0s 678us/step - loss: 0.6801 - accuracy: 

In [936]:
y_pred = ann.predict(X_test)
print(y_pred)
y_pred = (y_pred > 0.9)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1)) #used reshape to print vertically

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall", recall_score(y_test, y_pred, pos_label=0, average='binary'))

print("Precision", precision_score(y_test, y_pred, pos_label=0,  average='binary'))


3/3 [==============================] - 0s 1ms/step
[[0.4659512 ]
 [0.33276248]
 [0.35998717]
 [0.40487817]
 [0.30132285]
 [0.44119442]
 [0.45328525]
 [0.2971627 ]
 [0.36255476]
 [0.51187   ]
 [0.5221817 ]
 [0.36458474]
 [0.3093476 ]
 [0.53823566]
 [0.3598737 ]
 [0.6658264 ]
 [0.3589058 ]
 [0.36044675]
 [0.36332634]
 [0.48219988]
 [0.5149302 ]
 [0.29961488]
 [0.36156642]
 [0.48437387]
 [0.3607742 ]
 [0.38884747]
 [0.35954198]
 [0.36334625]
 [0.42883635]
 [0.35874474]
 [0.2994453 ]
 [0.49527764]
 [0.4753256 ]
 [0.35788548]
 [0.33955848]
 [0.5646079 ]
 [0.30509523]
 [0.46698707]
 [0.47339076]
 [0.2840412 ]
 [0.36335337]
 [0.3172488 ]
 [0.53567356]
 [0.35979873]
 [0.3631045 ]
 [0.36081678]
 [0.8692262 ]
 [0.3223638 ]
 [0.67368734]
 [0.53695375]
 [0.46581316]
 [0.5047658 ]
 [0.427644  ]
 [0.35869998]
 [0.4636679 ]
 [0.5052315 ]
 [0.38884747]
 [0.47787577]
 [0.8692262 ]
 [0.51187   ]
 [0.5891263 ]
 [0.47644848]
 [0.30018413]
 [0.31339276]
 [0.36036006]
 [0.47644848]
 [0.43136322]
 [0.3511402

In [903]:
# 1024*3